-- Postal Locale File
-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/postal/localization/

local AL3 = LibStub("AceLocale-3.0")
local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local L = AL3:NewLocale("Postal", "enUS", true, debug)
if L then
L["A button that collects all attachments and coins from mail."] = true
L["Add check boxes to the inbox for multiple mail operations."] = true
L["Add Contact"] = true
L["Add multiple item mail tooltips"] = true
L["Adds a contact list next to the To: field."] = true
L["AH-related mail"] = true
L["Alts"] = true
L["Autofill last person mailed"] = true
L["Auto-Send on Alt-Click"] = true
L["BlackBook"] = true
L["Block incoming trade requests while in a mail session."] = true
L["|cffeda55fAlt-Click|r to send this item to %s."] = true
L["|cffeda55fCtrl-Click|r to return it to sender."] = true
L["|cffeda55fShift-Click|r to take the contents."] = true
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).
|cFFFFCC00*|r Mousewheel to scroll the inbox.]=] ] = true
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = true
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = true
L["Choose"] = true
L["Clear list"] = true
L["Collected"] = true
L["Contacts"] = true
L["Copy From"] = true
L["Delete"] = true
L["Disable Blizzard's auto-completion popup menu"] = true
L["DoNotWant"] = true
L["Enable Alt-Click to send mail"] = true
L["Express"] = true
L["Friends"] = true
L["Guild"] = true
L["Help"] = true
L["In Progress"] = true
L["Keep free space"] = true
L["Mouse click short cuts for mail."] = true
L["Mousewheel to scroll Inbox"] = true
L["Name auto-completion options"] = true
L["New Profile"] = true
L["New Profile Name:"] = true
L["Non-AH related mail"] = true
L["Not taking more items as there are now only %d regular bagslots free."] = true
L["Open"] = true
L["OpenAll"] = true
L["Open All"] = true
L["Open all Auction cancelled mail"] = true
L["Open all Auction expired mail"] = true
L["Open all Auction successful mail"] = true
L["Open all Auction won mail"] = true
L["Open all mail with attachments"] = true
L["Open all Outbid on mail"] = true
L["Opening Speed"] = true
L["Other options"] = true
L["Part %d"] = true
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = true
L["Prints the amount of money collected during a mail session."] = true
L["Processing Message"] = true
L["Profile"] = true
L["Rake"] = true
L["Recently Mailed"] = true
L["Remove Contact"] = true
L["Reset Profile"] = true
L["Return"] = true
L["Select"] = true
L["Set subject field to value of coins sent if subject is blank."] = true
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = true
L["Skipping"] = true
L["Some Messages May Have Been Skipped."] = true
L["There are %i more messages not currently shown."] = true
L["There are %i more messages not currently shown. More should become available in %i seconds."] = true
L["TradeBlock"] = true
L["Use Postal's auto-complete"] = true
L["Verbose mode"] = true
L["Wire"] = true

if GetLocale() == "enUS" or GetLocale() == "enGB" then return end
end


local L = AL3:NewLocale("Postal", "ruRU")
if L then
L["A button that collects all attachments and coins from mail."] = "Кнопка, яка збирає усі монети і владення з пошти."
L["Add check boxes to the inbox for multiple mail operations."] = "Додає вікно для приміток в вхідній пошті для численних операцій."
L["Add Contact"] = "Додати контакт"
L["Add multiple item mail tooltips"] = "Додайте підказки пошти для кількох елементів."
L["Adds a contact list next to the To: field."] = "Додає список контактів в поле адресата."
L["AH-related mail"] = "Листи з аукціона"
L["Alts"] = "Альти"
L["Autofill last person mailed"] = "Ввести в рядок адреси нік останнього, кому було надіслано листа"
L["Auto-Send on Alt-Click"] = "Автовідправка по Alt+Клік"
L["BlackBook"] = "Черний список"
L["Block incoming trade requests while in a mail session."] = "Блокувати всі запити на торгівлю під час відправки масової пошти"
L["|cffeda55fAlt-Click|r to send this item to %s."] = "|cffeda55fAlt+Клік|r надіслати предмет на адресу %s."
L["|cffeda55fCtrl-Click|r to return it to sender."] = "|cffeda55fCtrl+Клік|r повернути відправнику."
L["|cffeda55fShift-Click|r to take the contents."] = "|cffeda55fShift+Клік|r взяти вміст."
L[ [=[|cFFFFCC00*|r Selected mail will be batch opened or returned to sender by clicking Open or Return.
|cFFFFCC00*|r You can Shift-Click 2 checkboxes to mass select every mail between the 2 checkboxes.
|cFFFFCC00*|r You can Ctrl-Click a checkbox to mass select or unselect every mail from that sender.
|cFFFFCC00*|r Select will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r Select will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Вибрана пошта буде вся відкрита або повернена відправнику, натиснувши кнопку "Відкрити" або "Повернення".
|cFFFFCC00*|r Ви можете натиснути Shift-Клік на 2 кнопки для мас вибору пошти між цими 2 кнопками.
|cFFFFCC00*|r Ви можете натиснути Ctrl-Клік по кнопці для мас вибору або скасування вибору всієї пошти даного відправника.
|cFFFFCC00*|r Вибравши, пошти ніколи не буде видалятися (пошта без тексту авто-видаляється грою після отримання з неї доданих до неї предметів або грошей).
|cFFFFCC00*|r Вибравши, буде пропускатися CoD пошта та пошта від Blizzardа.
|cFFFFCC00*|r Вимкніть Детальний режим для припинення спаму в чаті під час відкриття пошти.]=]
L[ [=[|cFFFFCC00*|r Shift-Click to take item/money from mail.
|cFFFFCC00*|r Ctrl-Click to return mail.
|cFFFFCC00*|r Alt-Click to move an item from your inventory to the current outgoing mail (same as right click in default UI).
|cFFFFCC00*|r Mousewheel to scroll the inbox.]=] ] = [=[|cFFFFCC00*|r Shift-Клік зняття з пошти предметів/грошей..
|cFFFFCC00*|r Ctrl-Клік повертає пошту.
|cFFFFCC00*|r Alt-Клік поміщає предмет із вашого інвентарю у вихідну пошту (у стандартному UI,правий-Клік).
|cFFFFCC00*|r Колесо миші прокручує скриньку вхідної пошти.]=]
L[ [=[|cFFFFCC00*|r Simple filters are available for various mail types.
|cFFFFCC00*|r Shift-Click the Open All button to override the filters and take ALL mail.
|cFFFFCC00*|r OpenAll will never delete any mail (mail without text is auto-deleted by the game when all attached items and gold are taken).
|cFFFFCC00*|r OpenAll will skip CoD mails and mails from Blizzard.
|cFFFFCC00*|r Disable the Verbose option to stop the chat spam while opening mail.]=] ] = [=[|cFFFFCC00*|r Прості фільтри доступні для різних типів пошти..
|cFFFFCC00*|r Shift-Клік по кнопці "Відкрити все" анулює фільтри та зніме всю пошту.
|cFFFFCC00*|r "Відкрити все" не видалятиме пошту (пошта без тексту авто-видаляється грою після отримання з неї доданих до неї предметів або грошей).
|cFFFFCC00*|r "Відкрити все" пропускатиме платіжну пошту та пошту від Blizzardа.
|cFFFFCC00*|r Вимкніть Детальний режим для припинення спаму в чаті під час відкриття пошти.]=]
L[ [=[|cFFFFCC00*|r This module will list your contacts, friends, guild mates, alts and track the last 10 people you mailed.
|cFFFFCC00*|r It will also autocomplete all names in your BlackBook.]=] ] = [=[|cFFFFCC00*|r цей модуль буде виводити список ваших контактів, друзів, товаришів гільдії, альтів і відстежувати останніх 10 людей, яким ви надіслали пошту.
|cFFFFCC00*|r Також будуть автозаповнені всі імена у вашому Чорному Списку.]=]
L["Choose"] = "Вибір"
L["Clear list"] = "Видалити список"
L["Collected"] = "Зібрано"
L["Contacts"] = "Контакти"
L["Copy From"] = "Копіювати з"
L["Delete"] = "Видалити"
L["Disable Blizzard's auto-completion popup menu"] = "Вимкніть спливаюче меню автозавершення Blizzard"
-- L["DoNotWant"] = "DoNotWant" -- Не хочу
L["Enable Alt-Click to send mail"] = "Включити посилку пошти Alt+Клік"
L["Express"] = "Експрес"
L["Friends"] = "Друзі"
L["Guild"] = "Гільдія"
L["Help"] = "Довідка"
L["In Progress"] = "Обробляю"
L["Keep free space"] = "Залиште вільний простір"
L["Mouse click short cuts for mail."] = "Особливі клацання миші при відкритій пошті"
L["Mousewheel to scroll Inbox"] = "Перегортати пошту коліском миші"
L["Name auto-completion options"] = "Параметри автозаповнення імен"
L["New Profile"] = "Новий профіль"
L["New Profile Name:"] = "Назва нового профія:"
L["Non-AH related mail"] = "Пошта не з аукціона"
L["Not taking more items as there are now only %d regular bagslots free."] = "Не беручи більше речей, оскільки зараз є лише %d звичайних місць в сумці."
L["Open"] = "Відкрити"
L["OpenAll"] = "Відкрити все"
L["Open All"] = "Відкрити все"
L["Open all Auction cancelled mail"] = "Відкривати всі листи про перервані аукціони"
L["Open all Auction expired mail"] = "Відкривати всі листи з аукціону, що не відбувся"
L["Open all Auction successful mail"] = "Відкрити всі листи з успішних аукціонів"
L["Open all Auction won mail"] = "Відкрити всі листи з виграним товаром"
L["Open all mail with attachments"] = "Відкрити всі листи з вкладеннями"
L["Open all Outbid on mail"] = "Відкрити всі листи з перебитими ставками"
L["Opening Speed"] = "Швидкість відкриття"
L["Other options"] = "Інші опції"
L["Part %d"] = "Частина %d"
L["Please post bugs or suggestions at the wowace forums thread at |cFF00FFFFhttp://forums.wowace.com/showthread.php?t=3909|r. When posting bugs, indicate your locale and Postal's version number v%s."] = "Будь ласка, повідомте про помилки або пропозиції на форумі wowace |cFF00FFFF http://forums.wowace.com/showthread.php?t=3909|r. Під час відправки помилки, повідомте мову вашого клієнта та номер версії Postalа v%s. Повідомлення про помилки з перекладу на українську мову приймаються тут |cFF00FFFF https://github.com/GreatsharkUA/WoW_Addons_UA|r. "
L["Prints the amount of money collected during a mail session."] = "Повідомити суму грошей, зібраних за сеанс роботи з поштою"
L["Processing Message"] = "Обробка повідомлення"
L["Profile"] = "Профіль"
L["Rake"] = "Підрахунок"
L["Recently Mailed"] = "Нещодавні кореспонденти"
L["Remove Contact"] = "Видалити контакт"
L["Reset Profile"] = "Скинути Профіль"
L["Return"] = "Повернути"
L["Select"] = "Вибір"
L["Set subject field to value of coins sent if subject is blank."] = "Пише у темі листа кількість монет, якщо тема не задана"
L["Shows a clickable visual icon as to whether a mail will be returned or deleted on expiry."] = "Показує візуальний значок, який можна натиснути, щоб визначити, чи буде пошта повернена чи видалена після закінчення терміну дії."
L["Skipping"] = "Пропускаємо"
L["Some Messages May Have Been Skipped."] = "Деякі повідомлення були пропущені."
L["There are %i more messages not currently shown."] = "Є ще %i повідомлень, які зараз не відображаються."
L["There are %i more messages not currently shown. More should become available in %i seconds."] = "Є ще %i повідомлень, які зараз не відображаються. Більше має стати доступним через %i секунд."
L["TradeBlock"] = "Блокувати торгівлю"
L["Use Postal's auto-complete"] = "Використовуйте автозаповнення Postal"
L["Verbose mode"] = "Детальний режим"
L["Wire"] = "Оцінка"

return
end
