--[[
	Bagnon Config Localization Information: Ukrainian localization
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'ruRU')
if not L then return end

L.Columns = 'Стовпці'
L.Scale = 'Маштаб'
L.Spacing = 'Інтервал'
L.Opacity = 'Прозорість'
L.FrameColor = 'Колір рамки'
L.FrameBorderColor = 'Колір бордюрю рамки'
L.Frame = 'Рамка'
L.Inventory = 'Інвентарь'
L.Bank = 'Банк'
L.KeyRing = 'Брелок'
L.GuildBank = 'Банк гільдії'
L.LockFramePositions = 'Зафіксуйте положення вікна'
L.ShowEmptyItemSlotBackground = 'Відображати фон для порожніх слотів предметів'
L.HighlightItemsByQuality = 'Виділіть предмети за якістю' 
L.HighlightQuestItems = 'Виділіть предмети квесту'
L.ReverseSlotOrdering = 'Зворотне відображення слотів \nдля сумок'
L.ColorItemSlotsByBagType = 'Розфарбуйте порожні слоти для предметів за типом сумки'
L.FrameLayer = 'Шар'
L.EnableBagFrame = 'Увімкнути кнопку сумки'
L.EnableMoneyFrame = 'Увімкнути зону золота'
L.EnableDBOFrame = 'Увімкнути databroker зону '
L.EnableSearchToggle = 'Увімкнути кнопку пошуку'
L.EnableOptionsToggle = 'Увімкнути кнопку налаштувань'
L.EnableFrame_inventory = 'Увімкнути зону інвентаря'
L.EnableFrame_bank = 'Увімкнути зону банку'
L.EnableFrame_keys = 'Увімкнути брелок'
L.SettingRequiresRestart = 'Це налаштування діятиме під час наступного входу'
L.EnableAutoDisplay_bank = 'Показувати інвентар при відвідуванні банку'
L.EnableAutoDisplay_ah = 'Показувати інвентар під час відвідування аукціонну'
L.EnableAutoDisplay_vendor = 'Показувати інвентар при відвідуванні торговця'
L.EnableAutoDisplay_trade = 'Показувати інвентар під час торгівлі предметами'
L.EnableAutoDisplay_craft = 'Показувати інвентар під час крафта'
L.EnableAutoDisplay_mail = 'Показувати інвентар при перевірці поштової скриньки'
L.EnableAutoDisplay_guildbank = 'Показувати інвентар під час відвідування банку гільдії'
L.EnableAutoDisplay_player = 'Показувати інвентар при відкритті вікна гравця'
L.DisplaySettings = 'Автоматично відображати вінко інвентарю'
L.DisplaySettingsTitle = 'Налаштування автоматичного відображення вікна'
L.FrameSettings = 'Параметри вікна'
L.FrameSettingsTitle = 'Параметри конфігурації, специфічні для вінка Bagnon'
L.GeneralSettings = 'Загальні налаштування'
L.GeneralSettingsTitle = 'Загальні налаштування конфігурації Bagnon'
L.EnableBlizzardBagPassThrough = 'Показати рамки Blizzard для вимкнутих сумок'
L.EnableBagBreak = 'Увімкнути розкладку сумки'
L.ColorSettings = 'Параметри кольору'
L.ColorSettingsTitle = 'Параметри забарвлення слотів предметів'
L.ItemHighlightOpacity = 'Яскравість виділення предмета'
L.ItemSlotColor_ammo = 'Колір слота сумки для патронів'
L.ItemSlotColor_trade = 'Колір слота для торгової сумки'
L.ItemSlotColor_shard = 'Колір слота для сумки душ'
L.ItemSlotColor_keyring = 'Колір слота для ключів'
